### ISSUE TITLE
Unable to sync main data via flow

### ISSUE THREAD

**Issue by Yash-Garg** [DrewCarlson/qBittorrent-Kotlin#19]
I am using the `syncMainData` flow but `mainData` doesn't update the `torrents` list. If I remove a torrent from the client, it works and updates the `torrentsRemoved` list.

I also tried using the `getTorrents()` method with `asFlow()`, it also did not give any updates to the list of torrents in qbit app.

Not sure what am I doing wrong here. Any help would be appreciated!

```kotlin
client.syncMainData().collect { mainData ->
            _uiState.update { state -> state.copy(dataLoading = false, data = mainData) }
            Log.i("syncData", mainData.toString())
        }
```

Same issue happens with the `categories` list also. Also on which API version is this client based on?

![image](https://user-images.githubusercontent.com/33605526/176745182-51617ae4-32df-44bd-9d28-cbb5fb9c824e.png)

**Comment by DrewCarlson** [comment]
Thanks for the report, please try version `0.5.2`.  `syncMainData()` and `torrentFlow(hash)` are the only methods which will provide updated models.

**Comment by Yash-Garg** [comment]
> Thanks for the report, please try version `0.5.2`. `syncMainData()` and `torrentFlow(hash)` are the only methods which will provide updated models.

I'll try the new version and report back, thanks for the quick response!

**Comment by Yash-Garg** [comment]
`torrents` and `tags` are syncing perfectly now! Also, when I'm adding a category it's still not updating the `categories` array in `mainData` (Deletion of category gets updated in the `categoriesRemoved` array).

**Comment by DrewCarlson** [comment]
Sorry, missed a bit for merging new category items.  Try `0.5.3` which will be available shortly, or `0.5.4-SNAPSHOT` is available now.

**Comment by Yash-Garg** [comment]
> Sorry, missed a bit for merging new category items. Try `0.5.3` which will be available shortly, or `0.5.4-SNAPSHOT` is available now.

Yup, it's working fine now. Thank you for the quick fixes!

**Comment by Yash-Garg** [comment]
Hey @DrewCarlson,

When I'm collecting the `syncMainData()` flow, I am unable to catch the exceptions thrown by the Flow.

When the data is loaded through the client once and if I close the qbit server, it throws an exception.

```gradle
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
    Process: dev.yashgarg.qbit, PID: 3092
    qbittorrent.QBittorrentException: io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=http://100.108.60.89:55455/api/v2/sync/maindata?rid=15, connect_timeout=3000 ms]
        at qbittorrent.ErrorTransformer$install$2.invokeSuspend(ErrorTransformer.kt:33)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7cf63d0, Dispatchers.Default]
    Caused by: io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=http://100.108.60.89:55455/api/v2/sync/maindata?rid=15, connect_timeout=3000 ms]
        at io.ktor.client.plugins.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:209)
        at io.ktor.client.engine.android.AndroidURLConnectionUtilsKt.timeoutAwareConnection(AndroidURLConnectionUtils.kt:62)
        at io.ktor.client.engine.android.AndroidURLConnectionUtilsKt$timeoutAwareConnection$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        	... 4 more
     Caused by: java.net.SocketTimeoutException: failed to connect to /100.108.60.89 (port 55455) from /10.0.2.16 (port 36402) after 3000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
        at libcore.io.IoBridge.connect(IoBridge.java:180)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/AndroidRuntime:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at io.ktor.client.engine.android.AndroidClientEngine$execute$2.invoke(AndroidClientEngine.kt:91)
        at io.ktor.client.engine.android.AndroidClientEngine$execute$2.invoke(AndroidClientEngine.kt:90)
        at io.ktor.client.engine.android.AndroidURLConnectionUtilsKt.timeoutAwareConnection(AndroidURLConnectionUtils.kt:57)
        at io.ktor.client.engine.android.AndroidClientEngine.execute(AndroidClientEngine.kt:90)
        at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:99)
```

I tried doing the following:

```kotlin
client.syncMainData()
      .onEach { data -> updateData(data) }
      .catch { err -> emitException(err) }
      .collect()
```

Also tried adding a `CoroutineExceptionHandler`, but got no success!

**Comment by DrewCarlson** [comment]
Try `v0.6.0` and let me know how it works for your application.

The original mechanism for transforming Ktor/HTTP errors was built for Ktor v1 and no longer produces the desired results.  I've reworked all error handling and the syncing flows now throw errors to use with operators like `catch` and `retry`.

**Comment by Yash-Garg** [comment]
> Try `v0.6.0` and let me know how it works for your application.
> 
> The original mechanism for transforming Ktor/HTTP errors was built for Ktor v1 and no longer produces the desired results. I've reworked all error handling and the syncing flows now throw errors to use with operators like `catch` and `retry`.

Thank you so much! I'll test and let you know.

**Comment by DrewCarlson** [comment]
Or try `v0.6.1`.  I've added support for uploading torrent files:

```kotlin
client.addTorrent {
    torrents.add("~/Downloads/my.torrent")
    // Or read files manually:
    // rawTorrents["my.torrent"] = getFileBytes()
}
```

Note that file paths in `torrents` are not validated, expect `QBittorrentException`s with a `400` status if you do not check existence and readability.

**Comment by Yash-Garg** [comment]
> Try `v0.6.0` and let me know how it works for your application.
> 
> The original mechanism for transforming Ktor/HTTP errors was built for Ktor v1 and no longer produces the desired results. I've reworked all error handling and the syncing flows now throw errors to use with operators like `catch` and `retry`.

The app doesn't crash like earlier now, the data sync just stops. But no error is shown in Log through the `Flow` catch block or with a `CoroutineExceptionHandler`.

**Comment by DrewCarlson** [comment]
Try `v0.6.2`, I've fixed and added tests for the sync flow.  There is also a workaround for a KTOR bug that caused authentication to loop until the session token was alphanumeric.

**Comment by Yash-Garg** [comment]
> Try `v0.6.2`, I've fixed and added tests for the sync flow. There is also a workaround for a KTOR bug that caused authentication to loop until the session token was alphanumeric.

It works fine now!

**Comment by Yash-Garg** [comment]
I am facing an issue when I am trying to reconnect the client after it fails once using a `SwipeRefreshLayout`. After refreshing, I get the client version successfully from client but it still throws a `CancellationException` which is not catchable as it is wrapped inside `QbittorrentException`.

```gradle
I/ClientManager: Client App Version - v4.4.3.1
E/ClientManager: qbittorrent.QBittorrentException: java.util.concurrent.CancellationException: Engine failed
```

How should I handle this?

**Comment by DrewCarlson** [comment]
Can you share what http engine you are using and what the request code looks like?  All exceptions from the client will be a `QBittorrentException` containing either the cause exception or a failed http response.

For the sync endpoints, you can use retry/catch to handle the exceptions: 
```kotlin
client.observeMainData()
        .retry { throwable ->
            (throwable as? QBittorrentException).code != 401
        }
        .collect()
```

**Comment by Yash-Garg** [comment]
> Can you share what http engine you are using and what the request code looks like? All exceptions from the client will be a `QBittorrentException` containing either the cause exception or a failed http response.
> 
> For the sync endpoints, you can use retry/catch to handle the exceptions:
> 
> ```kotlin
> client.observeMainData()
>         .retry { throwable ->
>             (throwable as? QBittorrentException)?.response?.status?.code != 401
>         }
>         .collect()
> ```

Sorry for the late response! Not getting much time these days, I'll try the retry functionality and get back to you. Thanks

**Comment by Yash-Garg** [comment]
Is there any method through which I can get the trackers list? Like the one mentioned in the [WebAPI](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-trackers).

**Comment by DrewCarlson** [comment]
There is now, I've added `client.getTrackers(hash)` in [`v1.0.0-alpha02`](https://github.com/DrewCarlson/qBittorrent-Kotlin/releases/tag/v1.0.0-alpha02)

**Comment by Yash-Garg** [comment]
> There is now, I've added `client.getTrackers(hash)` in [`v1.0.0-alpha02`](https://github.com/DrewCarlson/qBittorrent-Kotlin/releases/tag/v1.0.0-alpha02)

Thank you for the fast changes! Appreciate it.

**Comment by Yash-Garg** [comment]
Is there any method for getting the peers data too? [Reference](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-peers-data)

**Comment by DrewCarlson** [comment]
Try `observeTorrentPeers(hash)` in [`v1.0.0-alpha03`](https://github.com/DrewCarlson/qBittorrent-Kotlin/releases/tag/v1.0.0-alpha03)

**Comment by Yash-Garg** [comment]
When I'm trying to log the exception in `observeTorrent()` flow, I am not getting anything in the logs. I am removing the file from the server and checking in app to see if it throws an exception for file not found.

```kotlin
client.observeTorrent(hash)
    .catch { throwable ->
        Log.e(this::class.simpleName, throwable.toString())
        _uiState.update { state ->
            state.copy(
                error = FileNotFoundException(throwable.message),
                loading = false,
            )
        }
    }
    .collect { info ->
        // ui state updates here
    }
```

**Comment by DrewCarlson** [comment]
When the torrent hash you subscribe to does not exist on the server or is removed while subscribed, the Flow completes normally with no error.  You should only get error messages when something is not working correctly: i.e. the QBTClient is sending bad data or the server is unable to handle requests.

Seems like you want something like this to handle when the torrent is removed unexpectedly from the server/a different client:

```kotlin
client.observeTorrent(hash)
    .onEach { info ->
       // TODO: Handle ui state updates here
    }
    .catch { /* Optionally handle exception here or do nothing, ensuring `collect()` never throws. */ }
    .onComplete { throwable ->
       if (throwable == null) {
           // The file has been removed
       } else {
           // Process throwable, add error to ui state 
       }
    }
    .collect()
```

If you're seeing exceptions related to the syncing API requests thrown that are not caught in a flow like above, let me know but you can try an alternative Ktor client engine like CIO or OkHttp.

**Comment by DrewCarlson** [comment]
👍  FYI this behavior for removed torrents was just the obvious approach to keep the syncing logic simple (and free of too much HTTP handling code).  If you find it hard to get the desired result as is, I'm open to adding a `TorrentNotFoundException : QBittorrentException` for this case.

**Comment by Yash-Garg** [comment]
> 👍 FYI this behavior for removed torrents was just the obvious approach to keep the syncing logic simple (and free of too much HTTP handling code). If you find it hard to get the desired result as is, I'm open to adding a `TorrentNotFoundException : QBittorrentException` for this case.

No issues, I used the `onCompletion { ... }` block for managing the torrent not found case. It works fine with that, I am just passing a custom exception when `throwable` is null in `onCompletion` to the ui state.

**Comment by Yash-Garg** [comment]
> Try `observeTorrentPeers(hash)` in [`v1.0.0-alpha03`](https://github.com/DrewCarlson/qBittorrent-Kotlin/releases/tag/v1.0.0-alpha03)

I tried this method but I am not getting any data in the flow.

**Comment by DrewCarlson** [comment]
Can you try adding the Ktor [client logger](https://ktor.io/docs/client-logging.html) and sharing the logs after collecting the peers flow?

I originally only tested the new method in the demo program which worked as intended, I've since added a basic test which passes https://github.com/DrewCarlson/qBittorrent-Kotlin/commit/68f702f8234e9cc03fb6d04690b53ebaaaefb628

**Comment by Yash-Garg** [comment]
> Can you try adding the Ktor [client logger](https://ktor.io/docs/client-logging.html) and sharing the logs after collecting the peers flow?
> 
> I originally only tested the new method in the demo program which worked as intended, I've since added a basic test which passes [68f702f](https://github.com/DrewCarlson/qBittorrent-Kotlin/commit/68f702f8234e9cc03fb6d04690b53ebaaaefb628)

It works fine, my bad. The flow didn't start that's why it wasn't getting the data!

**Comment by Yash-Garg** [comment]
> Can you share what http engine you are using and what the request code looks like? All exceptions from the client will be a `QBittorrentException` containing either the cause exception or a failed http response.
> 
> For the sync endpoints, you can use retry/catch to handle the exceptions:
> 
> ```kotlin
> client.observeMainData()
>         .retry { throwable ->
>             (throwable as? QBittorrentException)?.response?.status?.code != 401
>         }
>         .collect()
> ```

I am trying to retry the connection with main data flow, but it keeps showing retrying and does not connect with the client.

For checking I turned the internet off of the emulator and then switched on, then the same loop happens.

Do you have any idea how can I possibly solve this? Thanks!

[Code Reference](https://github.com/Yash-Garg/qBittorrent-KT/blob/refactor/ui-tabs/app/src/main/kotlin/dev/yashgarg/qbit/ui/server/ServerViewModel.kt#L83-L90)

**Comment by DrewCarlson** [comment]
It would be helpful to have the Ktor [logging](https://ktor.io/docs/client-logging.html) feature enabled and share the complete logs for your scenario.

**Comment by DrewCarlson** [comment]
Try the latest snapshot build, your existing code should work.

**Comment by Yash-Garg** [comment]
> Try the latest snapshot build, your existing code should work.

Okay, will try. Thanks!

**Comment by Yash-Garg** [comment]
@DrewCarlson I am unable to use `HTTPS` domains for connection, I think the code below might be an issue regarding that. It will always connect with `HTTP` even if it's an `HTTPS` domain.
https://github.com/DrewCarlson/qBittorrent-Kotlin/blob/8a89af102a03b91262033ea8179f537f61d1d03c/client/src/commonMain/kotlin/QBittorrentClient.kt#L95

**Comment by Yash-Garg** [comment]
I'm getting **"Engine Failed"** error, probably it's failing to parse some JSON data. Using the latest SNAPSHOT build.

```kotlin
lb.y: java.util.concurrent.CancellationException: Engine failed
	at lb.w.d(SourceFile:320)
	at lb.e.f(Unknown Source:12)
	at da.a.s(Unknown Source:8)
	at q9.j.h(SourceFile:69)
	at q9.j.g(SourceFile:16)
	at q9.i.s(SourceFile:23)
	at da.a.s(Unknown Source:31)
	at q9.j.h(SourceFile:69)
	at q9.j.g(SourceFile:16)
	at q9.i.s(SourceFile:23)
	at da.a.s(Unknown Source:31)
	at q9.j.h(SourceFile:69)
	at q9.j.g(SourceFile:16)
	at q9.i.s(SourceFile:23)
	at da.a.s(Unknown Source:31)
	at q9.j.h(SourceFile:69)
	at q9.i.s(SourceFile:18)
	at da.a.s(Unknown Source:31)
	at q9.j.h(SourceFile:69)
	at q9.i.s(SourceFile:18)
	at da.a.s(Unknown Source:31)
	at q9.j.h(SourceFile:69)
	at q9.i.s(SourceFile:18)
	at da.a.s(Unknown Source:31)
	at q9.j.h(SourceFile:69)
	at q9.i.s(SourceFile:18)
	at da.a.s(Unknown Source:31)
	at kotlinx.coroutines.l0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.j0: [x1{Cancelling}@663d3a4, Dispatchers.Main.immediate]
Caused by: java.util.concurrent.CancellationException: Engine failed
	at z9.k.a(Unknown Source:2)
	at w8.k.a(SourceFile:19)
	at w8.k.W(SourceFile:17)
	at kotlinx.coroutines.p0.t(SourceFile:42)
	at kotlinx.coroutines.n1.H(SourceFile:97)
	at kotlinx.coroutines.n1.J(SourceFile:168)
	at kotlinx.coroutines.k1.t(SourceFile:25)
	at kotlinx.coroutines.n1.H(SourceFile:97)
	at kotlinx.coroutines.n1.J(SourceFile:168)
	at kotlinx.coroutines.n1.j0(SourceFile:220)
	at kotlinx.coroutines.n1.a0(SourceFile:5)
	at kotlinx.coroutines.a.s(SourceFile:14)
	at da.a.s(Unknown Source:31)
	at kotlinx.coroutines.l0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.e.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
Caused by: j9.f: Illegal input
	at k9.d.a(SourceFile:193)
	at j9.b.d(Unknown Source:73)
	at kotlinx.coroutines.flow.j.a(SourceFile:97)
	at j9.c.a(Unknown Source:13)
	at y9.p.S(SourceFile:73)
	at kotlinx.coroutines.d0.P(SourceFile:78)
	at q8.a.f(SourceFile:531)
	at q8.a.h(SourceFile:23)
	at q8.a.N(SourceFile:49)
	at q9.j.g(SourceFile:36)
	at q9.j.c(SourceFile:26)
	at q8.b.f(SourceFile:180)
	at q8.b.N(SourceFile:34)
	at q9.j.g(SourceFile:36)
	at q9.j.c(SourceFile:26)
	at q9.j.e(SourceFile:8)
	at w8.m.f(SourceFile:64)
	at w8.m.N(SourceFile:27)
	at q9.j.g(SourceFile:36)
	at q9.j.c(SourceFile:26)
	at q9.j.a(SourceFile:24)
	at q9.d.a(SourceFile:184)
	at r8.c.a(SourceFile:166)
	at kotlinx.coroutines.d0.C(SourceFile:76)
	at mb.i.a(SourceFile:279)
	at mb.f.f(Unknown Source:11)
	at da.a.s(Unknown Source:8)
	... 4 more
Caused by: db.i: Unexpected JSON token at offset 4289: Failed to parse int for input '2792450048' at path: $.peers['116.74.70.95:1031'].downloaded
JSON input: .....eed":0,"downloaded":2792450048,"files":"","flags":"d u I H X.....
	at y9.p.i(Unknown Source:32)
	at y9.p.h(Unknown Source:34)
	at db.z.o(SourceFile:62)
	at db.z.p(Unknown Source:12)
	at db.w.k(Unknown Source:35)
	at qa.p.D(Unknown Source:5)
	at nb.a0.e(SourceFile:151)
	at db.w.t(SourceFile:67)
	at qa.p.r(SourceFile:11)
	at db.w.r(SourceFile:49)
	at bb.r0.n(SourceFile:83)
	at bb.r0.k(Unknown Source:2)
	at bb.a.j(SourceFile:38)
	at bb.a.e(Unknown Source:5)
	at db.w.t(SourceFile:67)
	at qa.p.r(SourceFile:11)
	at db.w.r(SourceFile:49)
	at nb.d0.e(SourceFile:75)
	at db.w.t(SourceFile:67)
	at cb.b.b(SourceFile:25)
	at k9.d.a(SourceFile:102)
	... 30 more
```

**Comment by Yash-Garg** [comment]
I am facing an issue with the `banPeers()` method, I am passing a single peer in the format of `ip:port` but it keeps saying **"Not Found"** (I checked on the WebUI also and the peer is there). 

I tried banning on the WebUI and inspecting the request, it also passes some hash in the parameters

```bash
curl 'https://my.domain/api/v2/transfer/banPeers?l9eimlmv' \
  ...
  --data-raw 'hash=b08752c972c90ec0ab2844629273908a178973ca&peers=195.216.219.56%3A62184' \
  --compressed
```

Below is the function I am using:

```kotlin
fun banPeer(peer: TorrentPeer) {
    val peerAddr = "${peer.ip}:${peer.port}"

    viewModelScope.launch {
        when (val result = runCatching { client.banPeers(listOf(peerAddr)) }) {
            is Ok -> _status.emit("Successfully banned $peerAddr")
            is Err -> _status.emit(result.error.message ?: "Failed to ban peer")
        }
    }
}
```

<img src="https://user-images.githubusercontent.com/33605526/196508448-3f53fba9-81b2-4d31-a9c2-d3d7395561e1.png" height="850" />

**Comment by DrewCarlson** [comment]
Please use a new issue for future problems, github becomes significantly less usable after about 10 comments.

So I'm not sure what the value of the hash parameter is, it's not documented https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#ban-peers

I see that I've got an incorrect fragment in the peer URLs resulting in the 404. Will fix shortly.

**Comment by Yash-Garg** [comment]
> Please use a new issue for future problems, github becomes significantly less usable after about 10 comments.
> 
> So I'm not sure what the value of the hash parameter is, it's not documented https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#ban-peers
> 
> I see that I've got an incorrect fragment in the peer URLs resulting in the 404. Will fix shortly.

Sure, I'll create a new issue next time onwards.

Okay, I'll try checking after your fix if it works.

**Comment by DrewCarlson** [comment]
I've pushed the URL fix (snapshots take ~10 minutes to publish), let me know if it works without the hash.  The API docs have some conflicting/missing information so there may be other endpoints that need updates, I'll look at qBittorrent source code and confirm things later.

**Comment by Yash-Garg** [comment]
> I've pushed the URL fix (snapshots take ~10 minutes to publish), let me know if it works without the hash.  The API docs have some conflicting/missing information so there may be other endpoints that need updates, I'll look at qBittorrent source code and confirm things later.

Sure, I'll update if it works.

**Comment by Yash-Garg** [comment]
> I've pushed the URL fix (snapshots take ~10 minutes to publish), let me know if it works without the hash. The API docs have some conflicting/missing information so there may be other endpoints that need updates, I'll look at qBittorrent source code and confirm things later.

It's working now with the updated endpoint.
