### ISSUE TITLE
crash: unexpected JSON token at offset 

### ISSUE THREAD

**Issue by Yash-Garg** [DrewCarlson/qBittorrent-Kotlin#71]
I think the `tier` field value is coming as string / empty and it is expecting a `num` type.

Using the latest `SNAPSHOT` build.

Can this be caused due to an older qBittorrent version (v.4.3.9)?

```kotlin 
j9.f: Illegal input
 at k9.d.a(SourceFile:193)
 at j9.b.d(Unknown Source:73)
 at kotlinx.coroutines.flow.j.a(SourceFile:97)
 at j9.c.a(Unknown Source:13)
 at y9.v.P(SourceFile:73)
 at kotlinx.coroutines.d0.U(SourceFile:78)
 at q8.a.f(SourceFile:531)
 at q8.a.h(SourceFile:23)
 at q8.a.N(SourceFile:49)
 at q9.j.g(SourceFile:36)
 at q9.j.c(SourceFile:26)
 at q8.b.f(SourceFile:180)
 at q8.b.N(SourceFile:34)
 at q9.j.g(SourceFile:36)
 at q9.j.c(SourceFile:26)
 at q9.j.e(SourceFile:8)
 at w8.m.f(SourceFile:64)
 at w8.m.N(SourceFile:27)
 at q9.j.g(SourceFile:36)
 at q9.j.c(SourceFile:26)
 at q9.j.a(SourceFile:24)
 at q9.d.a(SourceFile:184)
 at r8.c.a(SourceFile:166)
 at lb.x.g(SourceFile:181)
 at lb.h.f(Unknown Source:12)
 at da.a.s(Unknown Source:8)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at q9.j.h(SourceFile:69)
 at q9.j.g(SourceFile:16)
 at q9.i.s(SourceFile:23)
 at da.a.s(Unknown Source:31)
 at kotlinx.coroutines.l0.run(Unknown Source:102)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7898)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Suppressed: kotlinx.coroutines.j0: [x1{Cancelling}@26bf20d, Dispatchers.Main.immediate]
Caused by: db.j: Unexpected JSON token at offset 92: Expected numeric literal at path: $[0].tier
JSON input: .....um_seeds":0,"status":2,"tier":"","url":"** [DHT] **"},{"msg".....
 at kotlinx.coroutines.d0.m(Unknown Source:32)
 at kotlinx.coroutines.d0.l(Unknown Source:34)
 at db.a0.o(SourceFile:62)
 at db.a0.p(Unknown Source:12)
 at db.a0.j(Unknown Source:221)
 at db.x.m(Unknown Source:2)
 at qa.p.F(Unknown Source:5)
 at nb.h0.e(SourceFile:84)
 at db.x.v(SourceFile:67)
 at qa.p.t(SourceFile:11)
 at db.x.t(SourceFile:49)
 at bb.u.k(SourceFile:8)
 at bb.a.j(SourceFile:38)
 at bb.a.e(Unknown Source:5)
 at db.x.v(SourceFile:67)
 at bb.a1.e(Unknown Source:13)
 at db.x.v(SourceFile:67)
 at cb.b.b(SourceFile:25)
 at k9.d.a(SourceFile:102)
 ... 62 more
```

**Comment by DrewCarlson** [comment]
Very annoying, thanks for the report.  Looks to have been reported to qBittorrent already https://github.com/qbittorrent/qBittorrent/issues/13302

Try the latest snapshot, I've added special handling for this case where it attempts to turn the string into an int or uses -1 otherwise.

**Comment by Yash-Garg** [comment]
> Very annoying, thanks for the report. Looks to have been reported to qBittorrent already [qbittorrent/qBittorrent#13302](https://github.com/qbittorrent/qBittorrent/issues/13302)
> 
> Try the latest snapshot, I've added special handling for this case where it attempts to turn the string into an int or uses -1 otherwise.

Thanks, will check out with the latest snapshot.

**Comment by Yash-Garg** [comment]
Works fine now!

**Comment by Yash-Garg** [comment]
@DrewCarlson is the latest snapshot published on maven?

**Comment by Yash-Garg** [comment]
> @DrewCarlson is the latest snapshot published on maven `v1.0.0-beta01`?

I need it so that I can publish the app on fdroid, as it doesn't support sonatype snapshot listing.

**Comment by Yash-Garg** [comment]
@DrewCarlson can you please publish the latest changes on maven central?

I need it so that I can publish my app on fdroid, as it doesn't support sonatype snapshot listing.

**Comment by DrewCarlson** [comment]
Version `1.0.0-beta02` has been published.
